#!/bin/bash

[ -n "$NANODLP_VERSION" ] || NANODLP_VERSION="8647"
[ -n "$NANODLP_BUILD" ] || NANODLP_BUILD="arm.rpi"

[ -n "$NANODLP_DISTRO" ] || NANODLP_DISTRO="generic"

[ -n "$NANODLP_DEPS" ] || NANODLP_DEPS="wget git apt install cmake \
libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev \
ttf-mscorefonts-installer fontconfig libsystemd-dev libinput-dev libudev-dev \
libxkbcommon-dev libraspberrypi0 libraspberrypi-dev libraspberrypi-doc \
libraspberrypi-bin raspberrypi-sys-mods"

[ -n "$NANODLP_URL" ] || NANODLP_URL="https://www.nanodlp.com/download/nanodlp/nanodlp.linux.${NANODLP_BUILD}.${NANODLP_VERSION}.tar.gz"
[ -n "$NANODLP_DSI_URL" ] || NANODLP_DSI_URL="https://www.nanodlp.com/download/nanodlp-dsi.beta.tar.gz"
