#!/usr/bin/env bash
# nanodlp install script
# Installs NanoDLP for use on the Prometheus MSLA Printer
# Written by Ada Phillips <ragwafire99@gmail.com
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap

check_install_pkgs ${NANODLP_DEPS}

pushd "/etc/systemd/system"
# Generate NanoDLP service file
echo """
[Unit]
Description=nanodlp service
Requires=klipper.service

[Service]
Type=simple
ExecStart=/home/${BASE_USER}/nanodlp/run.sh
RemainAfterExit=yes
WorkingDirectory=/home/${BASE_USER}/nanodlp
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
""" > nanodlp.service

echo """
[Unit]
Description=NanoDLP DSI service
After=nanodlp.service

[Service]
WorkingDirectory=/home/${BASE_USER}/nanodlp-hmi/
ExecStart=/home/${BASE_USER}/nanodlp-hmi/dsi --release app
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
""" > nanodlp-hmi.service

popd

pushd "/home/${BASE_USER}"
sudo -u "${BASE_USER}" mkdir -p nanodlp
sudo -u "${BASE_USER}" mkdir -p nanodlp-hmi

# Pi package has nested folder and renamed binary, for whatever reason
if [ $NANODLP_VERSION == "arm.rpi" ] ; then
    sudo -u "${BASE_USER}" wget ${NANODLP_URL} -O - | tar -C nanodlp/ -xz printer --strip-components=1
    sudo -u "${BASE_USER}" mv nanodlp/printer nanodlp/nanodlp
else
    sudo -u "${BASE_USER}" wget ${NANODLP_URL} -O - | tar -C nanodlp/ -xz
fi

# unpack beta DSI flutter app
sudo -u "${BASE_USER}" wget ${NANODLP_DSI_URL} -O - | tar -C nanodlp-dsi/ -xz

sudo -u "${BASE_USER}" echo -n "${NANODLP_DISTRO}">nanodlp/build
[[ -e nanodlp/distrop/"${NANODLP_DISTRO}"/req/* ]] && sudo -u "${BASE_USER}" cp -rf nanodlp/distro/"${NANODLP_DISTRO}"/req/* nanodlp/
[[ -e nanodlp/distrop/"${NANODLP_DISTRO}"/req/* ]] && sudo -u "${BASE_USER}" cp -rn nanodlp/distro/"${NANODLP_DISTRO}"/opt/* nanodlp/
ldconfig
popd

# Set config.txt values for optimal nanodlp
#set_config_var 'disable_camera_led' '1'
#set_config_var 'gpu_mem' '128'
#set_config_var 'dtoverlay' 'pi3-disable-bt'
#set_config_var 'disable_splash' '1'
#set_config_var 'boot_delay' '0'
#set_config_var 'dtoverlay' 'vc4-fkms-v3d'
#set_config_var 'display_auto_detect' '1'
#set_config_var 'max_framebuffers' '2'
#set_config_var 'disable_overscan' '1'
#set_config_var 'arm_boost' '1'
#set_config_var 'framebuffer_width' '2160'
#set_config_var 'framebuffer_height' '3600'
#set_config_var 'hdmi_force_hotplug' '1'
#set_config_var 'dtparam' 'i2c_arm=on'
#set_config_var 'enable_uart' '1'
#set_config_var 'dtoverlay' 'waveshare35a'
#set_config_var 'hdmi_group' '2'
#set_config_var 'hdmi_mode' '1'
#set_config_var 'hdmi_mode' '87'
#set_config_var 'hdmi_cvt' '2160 3600 24'
#set_config_var 'hdmi_drive' '2'

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/usr/lib /usr/lib root

systemctl_if_exists enable nanodlp.service
systemctl_if_exists enable nanodlp-hmi.service
