#!/bin/bash
[ -n "$USER_RENAME_FILES" ] || USER_RENAME_FILES="/etc/systemd/system/klipper.service \
/etc/systemd/system/nanodlp.service \
/etc/systemd/system/nanodlp-hmi.service \
/etc/systemd/system/moonraker.service \
/home/$BASE_USER/printer_data/systemd/moonraker.env \
/home/$BASE_USER/printer_data/config/printer.cfg \
/home/$BASE_USER/printer_data/config/odyssey.yaml \
/etc/systemd/system/sl1_watcher.service \
/etc/systemd/system/odyssey.service \
/etc/systemd/system/orion.service \
/etc/nginx/sites-available/mainsail \
/home/$BASE_USER/klippy-env/bin/pip"