#!/usr/bin/env bash
# User Rename Script
# Rewrites known user-mentions to account for rpi imager username changes
# Written by Ada Phillips <ragwafire99@gmail.com>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap

pushd "/etc/systemd/system"
# Rename Service File
echo """
[Unit]
Description=Finalize user renaming, if applicable

[Install]
WantedBy=basic.target

[Service]
Type=oneshot
User=root
ExecStart=/rename_script.sh ${BASE_USER} ${USER_RENAME_FILES}
""" > user_rename.service

popd

unpack /filesystem/root / root

systemctl_if_exists enable user_rename.service
