#!/bin/bash
[ -n "$PROMETHEUS_CONFIG_REPO_SHIP" ] || PROMETHEUS_CONFIG_REPO_SHIP=https://github.com/TheContrappostoShop/Prometheus_Config.git
[ -n "$PROMETHEUS_CONFIG_REPO_BRANCH" ] || PROMETHEUS_CONFIG_REPO_BRANCH=main

[ -n "$PROMETHEUS_CONFIG_DIRS" ] || PROMETHEUS_CONFIG_DIRS="/home/${BASE_USER}/klipper /home/${BASE_USER}/printer_data/config /home/${BASE_USER}/printer_data/gcodes /home/${BASE_USER}/nanodlp/db"