#!/usr/bin/env bash
# Prometheus Config install script
# Installs the configuration files for the Prometheus MSLA Printer
# Written by Ada Phillips <ragwafire99@gmail.com>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap


pushd "/home/${BASE_USER}"

gitclone PROMETHEUS_CONFIG_REPO prometheus_config

for dir in ${PROMETHEUS_CONFIG_DIRS}; do
    sudo -u "${BASE_USER}" mkdir -p "${dir}"
done

sudo -u "${BASE_USER}" cp prometheus_config/klipper/.config klipper/
sudo -u "${BASE_USER}" cp prometheus_config/klipper/config/* printer_data/config/

# Only copy nanodlp files if neccessary
if [[ $MODULES == *"nanodlp"* ]]; then
    sudo -u "${BASE_USER}" cp prometheus_config/nanodlp/* nanodlp/db/
fi

# if mainsail and/or odyssey are included in this build, then include the relevant
# klipper configs at the head of printer.cfg
if [[ $MODULES == *"mainsail"* ]]; then
    sudo -u "${BASE_USER}" sed -i '1s;^;[include mainsail.cfg]\n;' printer_data/config/printer.cfg
fi

if [[ $MODULES == *"odyssey"* ]]; then
    sudo -u "${BASE_USER}" sed -i '1s;^;[include odyssey.cfg]\n;' printer_data/config/printer.cfg
fi

# Setup screen config
echo """
framebuffer_width=2160
framebuffer_height=3600
hdmi_force_hotplug=1
dtparam=i2c_arm=on
enable_uart=1
dtoverlay=waveshare35a
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt=2160 3600 24
hdmi_drive=2
disable_splash=1
""" >> /boot/config.txt

sed -i 's/vc4-kms-v3d/vc4-fkms-v3d/g' /boot/config.txt
