#!/usr/bin/env bash
# openocd install script
# Installs all of the OpenOCD dependencies, and clones the repo
# Written by Ada Phillips <ragwafire99@gmail.com
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap

check_install_pkgs ${OPENOCD_DEPS}

pushd "/home/${BASE_USER}"
gitclone OPENOCD_REPO openocd
popd

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
