#!/usr/bin/env bash
# nanodlp install script
# Installs Odyssey for use on the Prometheus MSLA Printer
# Written by Ada Phillips <ragwafire99@gmail.com
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap

pushd "/home/${BASE_USER}"
sudo -u "${BASE_USER}" mkdir -p odyssey

LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/TheContrappostoShop/Odyssey/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
ODYSSEY_URL="https://github.com/TheContrappostoShop/Odyssey/releases/download/$LATEST_VERSION/odyssey.tar.gz"

sudo -u "${BASE_USER}" wget ${ODYSSEY_URL} -O - | tar -C odyssey/ -xz

# Create scripts for starting and stopping odyssey prints (stop is *unsafe*)
echo """
#!/usr/bin/env bash

/home/${BASE_USER}/odyssey/odyssey --config /home/${BASE_USER}/odyssey/odyssey.yaml --file ${1} &>> /home/${BASE_USER}/printer_data/logs/odyssey.log &
""" > printer_data/scripts/odyssey_start.sh

echo """
#!/usr/bin/env bash
killall odyssey
""" > printer_data/scripts/odyssey_stop.sh

popd
