#!/usr/bin/env bash
# nanodlp install script
# Installs Odyssey for use on the Prometheus MSLA Printer
# Written by Ada Phillips <ragwafire99@gmail.com
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

install_cleanup_trap

check_install_pkgs ${ODYSSEY_DEPS}

pushd "/home/${BASE_USER}"
sudo -u "${BASE_USER}" mkdir -p odyssey

LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/TheContrappostoShop/Odyssey/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
ODYSSEY_URL="https://github.com/TheContrappostoShop/Odyssey/releases/download/$LATEST_VERSION/odyssey.tar.gz"

sudo -u "${BASE_USER}" wget ${ODYSSEY_URL} -O - | tar -C odyssey/ -xz

popd

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"

# Create file watcher service to generate .gcode files from uploaded .sl1 files
pushd "/etc/systemd/system"
echo """[Unit]
Description=Create Odyssey gcode files for every SL1 file uploaded
After=klipper.service

[Service]
ExecStart=/home/${BASE_USER}/odyssey/sl1_watcher.sh
RemainAfterExit=true
Type=simple
User=${BASE_USER}

[Install]
WantedBy=multi-user.target
""" > sl1_watcher.service

echo """[Unit]
Description=Run Odyssey Print Control Software
After=klipper.service

[Service]
ExecStart=/home/${BASE_USER}/odyssey/odyssey
RemainAfterExit=true
WorkingDirectory=/home/${BASE_USER}/odyssey
Restart=always
RestartSec=10
Type=simple
User=${BASE_USER}

[Install]
WantedBy=multi-user.target
""" > odyssey.service

systemctl_if_exists enable sl1_watcher.service
systemctl_if_exists enable odyssey.service

popd
