#!/bin/bash
[ -n "$KLIPPER_SRC_DIR" ] || KLIPPER_SRC_DIR=/home/${BASE_USER}/klipper
[ -n "$KLIPPER_PYTHON_DIR" ] || KLIPPER_PYTHON_DIR=/home/${BASE_USER}/klippy-env

[ -n "$PRINTER_DIR" ] || PRINTER_DIR=/home/${BASE_USER}/printer_data

[ -n "$KLIPPER_REPO_SHIP" ] || KLIPPER_REPO_SHIP=https://github.com/Klipper3d/klipper.git
[ -n "$KLIPPER_REPO_BRANCH" ] || KLIPPER_REPO_BRANCH=master
[ -n "$KLIPPER_DEPS" ] || KLIPPER_DEPS="wget git gpiod \
virtualenv python3-dev python3-matplotlib \
libffi-dev build-essential \
libncurses-dev libusb-dev \
avrdude gcc-avr binutils-avr avr-libc \
stm32flash dfu-util libnewlib-arm-none-eabi \
gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0"
[ -n "$KLIPPER_USER_GROUPS" ] || KLIPPER_USER_GROUPS=tty,dialout
[ -n "$KLIPPER_USER_DIRS" ] || KLIPPER_USER_DIRS="${PRINTER_DIR}/config ${PRINTER_DIR}/logs ${PRINTER_DIR}/gcode ${PRINTER_DIR}/comms ${PRINTER_DIR}/systemd"
[ -n "$KLIPPER_PYENV_REQ" ] || KLIPPER_PYENV_REQ=scripts/klippy-requirements.txt

[ -n "$KLIPPER_CONFIG" ] || KLIPPER_CONFIG="${PRINTER_DIR}/config/printer.cfg"
[ -n "$KLIPPER_SOCKET" ] || KLIPPER_SOCKET="${PRINTER_DIR}/comms/klippy.sock"
[ -n "$KLIPPER_LOG" ] || KLIPPER_LOG="${PRINTER_DIR}/logs/klippy.log"
[ -n "$KLIPPER_SERIAL" ] || KLIPPER_SERIAL="${PRINTER_DIR}/comms/klippy.serial"
