name: Build Image

on:
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build_nanodlp:
    uses: ./.github/workflows/build_variant.yml
    with:
      variant: nanodlp-based
  build_odyssey:
    uses: ./.github/workflows/build_variant.yml
    with:
      variant: odyssey-based

