name: Build Image

on:
  push:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build_nanodlp:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/build_variant.yml
      with:
        variant: nanodlp-based
  build_nanodlp:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/build_variant.yml
      with:
        variant: odyssey-based

